sudo: required
services:
  - docker

before_install:
  - docker build -t kandruch/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kandruch/react-test npm test -- --coverage

after_success:
  - docker build -t kandruch/multi-client ./client
  - docker build -t kandruch/multi-nginx ./nginx
  - docker build -t kandruch/multi-server ./server
  - docker build -t kandruch/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kandruch/multi-client
  - docker push kandruch/multi-nginx
  - docker push kandruch/multi-server
  - docker push kandruch/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-320262049302"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY